# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='celebrazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('orario', models.TimeField()),
                ('liturgia_celebrata', models.CharField(blank=True, max_length=200)),
                ('omelia_file', models.FileField(blank=True, upload_to='omelie/%Y/%m/%d/')),
                ('timecode_omelia', models.TimeField()),
                ('facebook', models.URLField(blank=True, max_length=1000)),
                ('youtube', models.URLField(blank=True, max_length=1000)),
                ('sito_web', models.URLField(blank=True, max_length=1000)),
                ('altro_1', models.URLField(blank=True, max_length=1000)),
                ('altro_2', models.URLField(blank=True, max_length=1000)),
                ('trascrizione_omelia', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('Persone_presenti', models.CharField(max_length=4)),
                ('luogo_celebrazione', models.CharField(choices=[('Altare maggiore', 'Altare maggiore'), ('Altare secondario', 'Altare secondario'), ('Altro locale', 'Altro locale'), ('Spazio aperto', 'Spazio aperto'), ('Altro', 'Altro')], max_length=30)),
                ('paramenti', models.CharField(choices=[('Casula', 'Casula'), ('Stola', 'Stola'), ('Pianeta', 'Pianeta'), ('Piviale', 'Piviale'), ('Altro', 'Altro')], max_length=30)),
                ('direzione_celebrazione', models.CharField(choices=[('Verso il popolo', 'Verso il popolo'), ('Altare a muro', 'Altare a muro'), ('Altro', 'Altro')], max_length=30)),
                ('animazione', models.CharField(choices=[('Corale', 'Corale'), ('Solista', 'Solista'), ('Registrazione', 'Registrazione'), ('Nessun canto', 'Nessun canto'), ('Altro', 'Altro')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'celebrazioni',
            },
        ),
        migrations.CreateModel(
            name='chiese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=250)),
                ('tipologia', models.CharField(choices=[('Cattedrale', 'Cattedrale'), ('Chiesa parrocchiale', 'Chiesa parrocchiale'), ('Chiesa rettorale', 'Chiesa rettorale'), ('Chiesa conventuale', 'Chiesa conventuale'), ('Altro', 'Altro')], default='Chiesa parrocchiale', max_length=30)),
                ('facebook', models.URLField(blank=True, max_length=1000)),
                ('youtube', models.URLField(blank=True, max_length=1000)),
                ('sito_web', models.URLField(blank=True, max_length=1000)),
                ('altro_1', models.URLField(blank=True, max_length=1000)),
                ('altro_2', models.URLField(blank=True, max_length=1000)),
                ('riferimenti_decreti', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'chiese',
            },
        ),
        migrations.CreateModel(
            name='diocesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=250)),
                ('riferimenti_decreti', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Diocesi',
            },
        ),
        migrations.CreateModel(
            name='persone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(choices=[('Vescovo diocesano', 'Vescovo diocesano'), ('Vescovo titolare', 'Vescovo titolare'), ('Sacerdote parroco', 'Sacerdote parroco'), ('Sacerdote', 'Sacerdote'), ('Diacono', 'Diacono'), ('Laico', 'Laico'), ('Altro', 'Altro')], default='Sacerdote parroco', max_length=30)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Persone',
            },
        ),
        migrations.CreateModel(
            name='regioni_ecclesiastiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'regioni ecclesiastiche',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'tag',
            },
        ),
        migrations.CreateModel(
            name='tipo_chiesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipologie chiese',
            },
        ),
        migrations.CreateModel(
            name='tipo_diocesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('regione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.regioni_ecclesiastiche')),
            ],
            options={
                'verbose_name_plural': 'Tipologie diocesi',
            },
        ),
        migrations.AddField(
            model_name='diocesi',
            name='tipologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.tipo_diocesi'),
        ),
        migrations.AddField(
            model_name='chiese',
            name='diocesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.diocesi'),
        ),
        migrations.AddField(
            model_name='celebrazione',
            name='luogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.chiese'),
        ),
        migrations.AddField(
            model_name='celebrazione',
            name='predicatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.persone'),
        ),
        migrations.AddField(
            model_name='celebrazione',
            name='tag_cloud',
            field=models.ManyToManyField(blank=True, null=True, to='telemesseTST.tag'),
        ),
    ]
