# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0002_remove_tipo_diocesi_regione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_diocesi',
            old_name='tipologia',
            new_name='denominazione',
        ),
    ]
