# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0003_auto_20200418_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocesi',
            name='regione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.regioni_ecclesiastiche'),
        ),
        migrations.AlterField(
            model_name='diocesi',
            name='tipologia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.tipo_diocesi'),
        ),
    ]
