# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0004_auto_20200418_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiese',
            name='luogo_e_indirizzo',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='Persone_presenti',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='animazione',
            field=models.CharField(blank=True, choices=[('Corale', 'Corale'), ('Solista', 'Solista'), ('Registrazione', 'Registrazione'), ('Nessun canto', 'Nessun canto'), ('Altro', 'Altro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='direzione_celebrazione',
            field=models.CharField(blank=True, choices=[('Verso il popolo', 'Verso il popolo'), ('Altare a muro', 'Altare a muro'), ('Altro', 'Altro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='luogo_celebrazione',
            field=models.CharField(blank=True, choices=[('Altare maggiore', 'Altare maggiore'), ('Altare secondario', 'Altare secondario'), ('Altro locale', 'Altro locale'), ('Spazio aperto', 'Spazio aperto'), ('Altro', 'Altro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='paramenti',
            field=models.CharField(blank=True, choices=[('Casula', 'Casula'), ('Stola', 'Stola'), ('Pianeta', 'Pianeta'), ('Piviale', 'Piviale'), ('Altro', 'Altro')], max_length=30),
        ),
    ]
