# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0005_auto_20200418_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiese',
            name='persone_collegate',
            field=models.ManyToManyField(to='telemesseTST.persone'),
        ),
        migrations.AddField(
            model_name='diocesi',
            name='vescovo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.persone'),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='omelia_file',
            field=models.FileField(blank=True, upload_to='omelie/'),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='tag_cloud',
            field=models.ManyToManyField(blank=True, to='telemesseTST.tag'),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='timecode_omelia',
            field=models.TimeField(blank=True),
        ),
    ]
