# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0008_auto_20200419_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrazione',
            name='Persone_presenti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celebrazione',
            name='predicatore',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.persone'),
        ),
        migrations.AlterField(
            model_name='chiese',
            name='persone_collegate',
            field=models.ManyToManyField(blank=True, help_text='Si possono selezionare pi\xf9 voci', to='telemesseTST.persone'),
        ),
    ]
