# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0009_auto_20200419_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrazione',
            name='link_trascrizione',
            field=models.URLField(blank=True, help_text='Inserire il link diretto alla trascrizione del testo, se pubblicata', max_length=1000),
        ),
        migrations.AddField(
            model_name='celebrazione',
            name='trascrizione_file',
            field=models.FileField(blank=True, help_text='Consente il caricamento sul server di qualunque tipo di file contenente la trascrizione', upload_to='omelie/trascrizioni/'),
        ),
    ]
