# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemesseTST', '0010_auto_20200419_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diocesi',
            name='vescovo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telemesseTST.persone'),
        ),
    ]
